# Generated by Django 4.0.7 on 2022-09-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemname',
            name='id',
        ),
        migrations.AlterField(
            model_name='systemname',
            name='sys_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
